import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata = { title: "Terms of Service — Skillify" };

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <Link
        href="/"
        className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors mb-8"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to home
      </Link>

      <h1 className="font-heading text-3xl font-extrabold text-foreground mb-2">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-8">Last updated: March 28, 2026</p>

      <div className="prose prose-sm max-w-none text-foreground space-y-6">
        <section>
          <h2 className="font-heading text-xl font-bold mb-2">1. Acceptance of Terms</h2>
          <p className="text-muted-foreground leading-relaxed">
            By accessing or using Skillify (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-xl font-bold mb-2">2. Use of the Service</h2>
          <p className="text-muted-foreground leading-relaxed">
            Skillify provides an AI-powered personalized learning platform. You agree to use the Service only for lawful purposes and in a manner that does not infringe the rights of others. You must be at least 13 years old to use the Service.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-xl font-bold mb-2">3. User Accounts</h2>
          <p className="text-muted-foreground leading-relaxed">
            You are responsible for maintaining the security of your account credentials. You must notify us immediately of any unauthorized use of your account. Skillify will not be liable for any loss resulting from unauthorized use of your account.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-xl font-bold mb-2">4. AI-Generated Content</h2>
          <p className="text-muted-foreground leading-relaxed">
            Course content, quizzes, and learning materials are generated by artificial intelligence. While we strive for accuracy, AI-generated content may contain errors. Always verify critical information with authoritative sources. Skillify makes no warranty regarding the accuracy, completeness, or fitness for a particular purpose of any AI-generated content.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-xl font-bold mb-2">5. Subscription and Billing</h2>
          <p className="text-muted-foreground leading-relaxed">
            Free plan users may generate up to 2 courses per month. Pro plan subscribers have access to unlimited courses and additional features. Subscriptions are billed monthly and may be cancelled at any time. No refunds are provided for partial months.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-xl font-bold mb-2">6. Intellectual Property</h2>
          <p className="text-muted-foreground leading-relaxed">
            The Skillify platform, including its design, code, and branding, is owned by Skillify. Course content generated for your account is yours to use for personal learning. You may not redistribute or commercialize AI-generated content from Skillify without permission.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-xl font-bold mb-2">7. Limitation of Liability</h2>
          <p className="text-muted-foreground leading-relaxed">
            Skillify is provided &quot;as is&quot; without warranties of any kind. In no event shall Skillify be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-xl font-bold mb-2">8. Changes to Terms</h2>
          <p className="text-muted-foreground leading-relaxed">
            We may update these terms from time to time. Continued use of the Service after changes constitutes your acceptance of the new terms. We will notify users of significant changes via email.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-xl font-bold mb-2">9. Contact</h2>
          <p className="text-muted-foreground leading-relaxed">
            For questions about these Terms of Service, please contact us through the app.
          </p>
        </section>
      </div>

      <div className="mt-8 pt-8 border-t border-primary/10 text-sm text-muted-foreground">
        <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link>
        {" · "}
        <Link href="/" className="hover:underline">Back to Skillify</Link>
      </div>
    </div>
  );
}
